name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and test with Docker
        run: |
          docker-compose build
          docker-compose run web npm test
          
      - name: Check for upstream changes
        run: ./scripts/check-upstream.sh 